master_ip : "10.5.0.2"
master_port: "7000"

slaves_port: ["8000", "9000"]
slaves_ips: ["10.5.0.3", "10.5.0.4"]


delivery_failure:
  kind: "server_unavailable" # server_unavailable, internal_loping
  servers_dead: [False, False]
  looping_sec: [0, 7] # for each server


heartbeat_seconds: 3

enforce_quorum: True
suspend_on_slaves_dead: True

sleep_duration_sec: 5

connection_timeout: 10

log_level: "DEBUG"