version: "3"

volumes:
  postgresql-db:

services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    volumes:
      - postgresql-db:/var/lib/postgresql/data
